name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t secure-demo .

      - name: Scan with Trivy (for CVEs)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secure-demo'
